version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apeboard_backend
    restart: always
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports: 
      - 3000:3000
    environment:
      NODE_ENV: development