version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apeboard_app
    restart: always
    depends_on:
      - cache
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports: 
      - 3000:3000
    environment:
      NODE_ENV: development
      RPC_URL: https://bsc-dataseed.binance.org/
      MASTERCHEF_ADDR: 0x0895196562C7868C5Be92459FaE7f877ED450452
  
  cache:
    image: redis:alpine
    container_name: apeboard_cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    command: redis-server --save 20 1

networks:
  default:
    name: apeboard_network