version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apeboard_app
    restart: always
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports: 
      - 3000:3000
    environment:
      NODE_ENV: development
  
  cache:
    image: redis:alpine
    container_name: apeboard_cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
  
networks:
  default:
    name: apeboard_network